version: '3.9'
services:
  booking-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
#      - my-db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

#volumes:
#  my-db: