version: '3.9'

services:
  booking-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#    ports:
#      - '3306:3306'
    volumes:
#      - my-db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 2s
      retries: 30
      
  booking-backend:
    build:
      context: booking-backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${MYSQL_HOST}
      DB_PORT: ${MYSQL_PORT}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3000:3000"
    depends_on:
      booking-db:
        condition: service_healthy
        
  booking-frontend:
    build:
      context: booking-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - booking-backend

#volumes:
#  my-db: